{{- if .Values.panda.enabled }}
# panda configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-envs
type: Opaque
stringData:
  PANDA_DB_BACKEND: "{{ .Values.panda.database.backend | default "postgres"}}"
  PANDA_DB_PASSWORD: {{ .Values.panda.database.password }}
  PANDA_DB_HOST: "{{ .Values.panda.database.dbhost | default (printf "%s-postgres" (include "panda_ref" .)) }}"
  PANDA_DB_PORT: "{{ .Values.panda.database.dbport }}"
  PANDA_DB_USER: "{{ .Values.panda.database.user | default "panda" }}"
  PANDA_DB_NAME: "{{ .Values.panda.database.name | default "panda_db" }}"

  PANDA_DB_SCHEMAPANDA: "{{ .Values.panda.database.schemapanda | default "DOMA_PANDA" }}"
  PANDA_DB_SCHEMAMETA: "{{ .Values.panda.database.schemameta | default "DOMA_PANDAMETA" }}"
  PANDA_DB_SCHEMAPANDAARCH: "{{ .Values.panda.database.schemapandaarch | default "DOMA_PANDAARCH" }}"
  PANDA_DB_SCHEMAJEDI: "{{ .Values.panda.database.schemajedi | default "DOMA_PANDA" }}"
  PANDA_DB_SCHEMADEFT: "{{ .Values.panda.database.schemadeft | default "DOMA_DEFT" }}"

  PANDA_URL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/server/panda"
  PANDA_URL_SSL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/server/panda"
  PANDA_BEHIND_REAL_LB: "1"
  PANDA_VERIFY_HOST: "off"
  PANDA_AUTH: "oidc"
  {{- if .Values.auth.auth_client_id }}
  # use internal token file instead of long-lived token string
  PANDA_AUTH_ID_TOKEN: "file:/tmp/proxies/panda_internal_token"
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}.internal
  {{- else }}
  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}
  {{- end }}

  {{- if .Values.panda.hostName }}
  PANDA_HOSTNAME: "{{ .Values.panda.hostName }}"
  {{- end }}

  # ActiveMQ
  PANDA_ACTIVEMQ_LIST: "{{ include "msgsvc_ref" . }}-activemq:61613"
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.msgsvc.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.msgsvc.basePasswd }}_jedi

  # iDDS
  PANDA_IDDS_HOST: "{{ include "idds_ref" . }}-rest"
  PANDA_IDDS_PORT: "{{ .Values.idds.restPort }}"
  PANDA_IDDS_AUTH_ID_TOKEN: "{{ .Values.auth.authIdToken }}"
  PANDA_IDDS_AUTH_VO: "{{ .Values.auth.authVO }}"
  
  # Rucio
  PANDA_RUCIO_HOST: "{{ .Values.rucio.rucioHost }}"
  PANDA_RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  PANDA_RUCIO_USERNAME: "{{ .Values.rucio.username }}"
  PANDA_RUCIO_PASSWORD: "{{ .Values.rucio.password }}"
  PANDA_RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"

  # CRIC
  {{- if .Values.cric.real }}
  PANDA_CRIC_CM: "{{ .Values.cric.costMetrix }}"
  PANDA_CRIC_DDMBLACKLIST: "{{ .Values.cric.ddmBlackList }}"
  PANDA_CRIC_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  PANDA_CRIC_URL_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  PANDA_CRIC_SCHEDCONFIG: "{{ .Values.cric.schedConfig }}"
  PANDA_CRIC_SITES: "{{ .Values.cric.sites }}"
  {{- else }}
  PANDA_CRIC_CM: "/var/cric/cm.json"
  PANDA_CRIC_DDMBLACKLIST: "/var/cric/ddm_blacklist.json"
  PANDA_CRIC_DDMENDPOINTS: "/var/cric/ddm_endpoints.json"
  PANDA_CRIC_URL_DDMENDPOINTS: "http://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/cric/ddm_endpoints.json"
  PANDA_CRIC_SCHEDCONFIG: "/var/cric/panda_queues.json"
  PANDA_CRIC_SITES: "/var/cric/sites.json"
  {{- end }}

  # proxy
  {{ include "set_proxy" . | indent 2 }}

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-certs
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/panda_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# auth
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-auth
type: Opaque
stringData:
  {{- range $client := .Values.auth.oidc.clients }}
  {{- $config_url := $.Values.auth.oidc.config_url }}
  {{- if $client.config_url }}
  {{- $config_url = $client.config_url }}
  {{- end }}
  {{- $audience := $.Values.auth.oidc.audience }}
  {{- if $client.audience }}
  {{- $audience = $client.audience }}
  {{- end }}
  {{ $client.name }}_auth_config.json: |-
    {{ $.Files.Get "files/panda_auths/auth_config.json.template" | replace "ROBOT_IDS" $client.robot_ids | replace "ID" $client.client_id | replace "SECRET" $client.client_secret | replace "URL" $config_url | replace "AUDIENCE" $audience  | replace "NAME" $client.name }}
  {{ end }}
  # add internal auth config if auth_client_id is set
  {{- if .Values.auth.auth_client_id }}
  {{ $.Values.auth.authVO }}.internal_auth_config.json: |-
    {{ $.Files.Get "files/panda_auths/auth_config.json.template" | replace "ROBOT_IDS" .Values.auth.auth_client_id | replace "ID" .Values.auth.auth_client_id | replace "URL" .Values.auth.auth_endpoint | replace "AUDIENCE" .Values.auth.oidc.audience | replace "NAME" "internal" }}
  {{- end }}

---
# token cache
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-token-cache
type: Opaque
stringData:
  {{- $token_cache := $.Values.auth.oidc.token_cache }}
  {{- $token_cache_dict := dict $token_cache.client_name (dict "client_id" $token_cache.client_id "secret" $token_cache.client_secret "endpoint" $token_cache.endpoint "use_token_key" true) }}
  # add internal token cache entry if auth_client_id is set
  {{- if .Values.auth.auth_client_id }}
    {{- $token_cache_dict := merge $token_cache_dict (dict "internal" (dict "client_id" .Values.auth.auth_client_id "secret" .Values.auth.auth_client_secret "endpoint" .Values.auth.auth_endpoint "token_file_path" "/tmp/proxies/panda_internal_token")) }}
  {{- end }}
  token_cache_config.json: |-
    {{ $token_cache_dict | toJson }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-tls-certs
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get "files/panda_certs/hostcert.pem" | b64enc }}
  tls.key: |-
    {{ $.Files.Get "files/panda_certs/hostkey.pem" | b64enc }}

{{- end }}
