# Default values for panda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jedi:
  replicaCount: 2
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 50Gi

  resources:
    limits:
      cpu: 4000m
      memory: 32Gi
    requests:
      cpu: 4000m
      memory: 32Gi

server:
  replicaCount: 2
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 500Gi

  resources:
    limits:
      cpu: 8000m
      memory: 32Gi
    requests:
      cpu: 8000m
      memory: 32Gi

  sharedCache: true

  # use Route class for ingress
  route:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: rubin-panda-server-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: default
        hosts:
          - domain: slac.stanford.edu
            hostOverride: rubin-panda-server-dev.slac.stanford.edu
  ingress_big:
    enabled: false
    hosts:
      - domain: slac.stanford.edu
        hostOverride: rubin-panda-server-big-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: default
        hosts:
          - domain: slac.stanford.edu
            hostOverride: rubin-panda-server-big-dev.slac.stanford.edu

postgres:
  enabled: false

  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 50Gi
