# Default values for bigmon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"
  # Set the below to true to use certificates from an existing secret (e.g. cert-manager issued certs)
  # If it's defined to a true value the helm-provided certificate files will be ignored.
  existingTlsSecret: ""

main:
  enabled: true

  image:
    tag: "v0.7.3"
    # tag: "v0.7.1"

  autoStart: true

  #persistentvolume:
  #  create: false         
  #  path: "/mnt/panda-bigmon-logs"
  #  size: 5Gi

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        # hostOverride: panda-k8s-dev-jedi.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ""
        hosts:
          - domain: cern.ch
            # hostOverride: panda-k8s-dev-jedi.cern.ch

  # use Route class to expose the service
  route:
    enabled: false
