# pv
{{- if .Values.persistentvolume.create }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}
  labels:
      {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  capacity:
    storage: {{ .Values.persistentvolume.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: {{ .Values.persistentvolume.path }}
---
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size }}
  {{- if .Values.persistentvolume.create }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "main.fullname" . }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "main.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "main.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/bin/sh", "-c"]
          args:
            - cp /data/bigmon/configmap/* /data/bigmon/config/ ;
              python /data/bigmon/config/process_template.py ;
              mv /data/bigmon/config/idds.cfg /opt/bigmon/etc/idds/ ;
              mv /data/bigmon/config/rucio.cfg /opt/bigmon/etc/ ;
              {{- if .Values.autoStart }}
              until /usr/pgsql-*/bin/pg_isready -h ${PANDA_DB_HOST} -p ${PANDA_DB_PORT}; do echo waiting for database; sleep 2; done;
              chmod 777 /data/bigmon/logs;
              start-daemon.sh all
              {{- else }}
              sleep infinity & wait
              {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              - name: {{ include "main.fullname" . }}-logs
                mountPath: /data/bigmon/logs
              - name: {{ include "main.fullname" . }}-sandbox
                mountPath: /data/bigmon/configmap
              - name: {{ include "main.fullname" . }}-certs
                mountPath: /opt/bigmon/etc/cert
          envFrom:
            - secretRef:
                name: {{ .Values.global.secret }}-bigmon-envs
          {{- if .Values.installedAppsList }}
          env:
            - name: BIGMON_INSTALLED_APPS_LIST
              value: "{{ .Values.installedAppsList }}"
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "main.fullname" . }}-sandbox
          configMap:
              name: {{ include "main.fullname" . }}-sandbox
        - name: {{ include "main.fullname" . }}-certs
          {{- if .Values.global.existingTlsSecret }}
          secret:
              secretName: {{ .Values.global.existingTlsSecret }}
              items:
                # Map the TLS keys to the filenames bigmon expects
                - key: tls.crt
                  path: hostcert.pem
                - key: tls.key
                  path: hostkey.pem
          {{- else }}
          secret:
              secretName: {{ .Values.global.secret }}-bigmon-certs
          {{- end }}
  {{- if .Values.persistentvolume.create }}
        - name: {{ include "main.fullname" . }}-logs
          persistentVolumeClaim:
            claimName: {{ include "main.fullname" . }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "main.fullname" . }}-logs
      spec:
        storageClassName: {{ .Values.persistentvolume.class }}
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.persistentvolume.size }}
  {{- end }}
