# Default values for bigmon.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
#

main:
  replicaCount: 1
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false

  hostName: "rubin-panda-bigmon-dev.slac.stanford.edu"

  installedAppsList: "core.art,core.buildmonitor,core.compare,core.errorsscattering,core.globalshares,core.grafana,core.iDDS,core.reports,core.runningprod,core.panda_client"

  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: rubin-panda-bigmon-dev.slac.stanford.edu
        paths:
          - path: /condor_logs
            pathType: Prefix
            serviceName: harvester-dev
            servicePort: 443
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: slac.stanford.edu
            hostOverride: rubin-panda-bigmon-dev.slac.stanford.edu
