name: Helm Charts

on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm-release.yml'
  push:
#    branches:
#      - main
    paths:
      - 'helm/**'
      - '.github/workflows/helm-release.yml'
  release:
    types: [published]

  workflow_dispatch:

jobs:
  lint:
    name: Lint charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint all charts
        run: |
          set -euo pipefail
          shopt -s nullglob
          for chart in helm/*; do
            if [ -d "$chart" ] && [ -f "$chart/Chart.yaml" ]; then
              echo "Building dependencies for ${chart}"
              helm dependency build "$chart"
              echo "Linting ${chart}"
              helm lint "$chart"
              echo "Packaging ${chart}"
              helm package "$chart" --destination packaged-charts
            fi
          done

      - name: Upload packaged charts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: helm-packages
          path: packaged-charts
          if-no-files-found: ignore

  release:
    name: Release charts
    needs: lint
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: helm
          charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          packages_dir: .cr-release-packages

